---
title: "Assignment 1"
author: "Simon Ganter, Josia John, Tudor Luchiean, Leif Maurer"
format: html
execute:
  cache: false 
---

\newpage

# Task 1: Geometrically Weighted Terms in ERGMs

## (1) Change statistic of gwodegree

### i.

Let $x'$ be the network obtained by adding a directed edge to a sender node that currently has out-degree $k\ge 1$ in $x$. Now:

$$
\begin{aligned}
s_\text{GWD}(x,\alpha) &= e^\alpha \cdot \sum_{i=1}^{n}\left(1 - \left(1-e^{-\alpha}\right)^i\right) \cdot D_i^\text{out}(x)\\
\\
s_\text{GWD}(x',\alpha) &= e^\alpha \cdot \left(\sum_{i=1}^{n}\left(1 - \left(1-e^{-\alpha}\right)^i\right) \cdot D_i^\text{out}(x) - \left(1 - \left(1-e^{-\alpha}\right)^k\right) + \left(1 - \left(1-e^{-\alpha}\right)^{k+1}\right)\right)\\
\\
\delta_\text{GWD}(k,\alpha) &= s_\text{GWD}(x',\alpha) - s_\text{GWD}(x,\alpha)\\
&= e^\alpha \cdot \left(- \left(1 - \left(1-e^{-\alpha}\right)^k\right) + \left(1 - \left(1-e^{-\alpha}\right)^{k+1}\right)\right)\\
&= e^\alpha \cdot \left(\left(1-e^{-\alpha}\right)^k - \left(1-e^{-\alpha}\right)^{k+1}\right)\\
&= e^a \cdot \left(1-e^{-\alpha}\right)^k \cdot \left(1 - \left(1-e^{-\alpha}\right)\right)\\
&= e^a \cdot \left(1-e^{-\alpha}\right)^k \cdot e^{-\alpha}\\
&= \left(1-e^{-\alpha}\right)^k\\
\end{aligned}
$$

For $k=0$ we get $\delta_\text{GWD}(0,\alpha) = e^\alpha \cdot \left(1 - \left(1-e^{-\alpha}\right)\right) = e^\alpha\cdot e^{-\alpha} = 1$. Note that this agrees with plugging in $k=0$ in the result above.

### ii.

```{r}
delta <- function(k, alpha) {
    return((1-exp(-alpha))^k)
}


f1 <- as.matrix(read.csv('../data/f1.csv'))
outdegrees <- rowSums(f1)
min <- min(outdegrees)
max <- max(outdegrees)

makeplot <- function(alphas) {
    x <- min:max
    ys <- lapply(alphas, function(a) delta(x, a))
    cols <- rainbow(length(alphas))

    plot(
    x, ys[[1]],
    type = "o",
    col = cols[1],
    ylim = range(unlist(ys)),
    xlab = "x",
    ylab = "delta(x, alpha)"
    )

    for (i in seq_along(alphas)) {
    lines(x, ys[[i]], type = "o", col = cols[i])
    }

    legend(
    "topright",
        legend = paste("alpha =", round(alphas, 3)),
        col = cols,
        lty = 1,
        pch = 1,
        cex = 0.8
    )
}

makeplot(c(-1))
makeplot(c(-0.5))
makeplot(c(0, 0.1, 0.2, 0.3, 0.5, log(2), 1, 2, 3))
```

### iii.

We can observe from the figures that the decay parameter $\alpha$ controls how quickly the marginal contribution of an additional out-edge decays with higher out-degree. As shown above, the marginal contribution simplifies to $(1-e^{-\alpha})^k$. For non-negative $\alpha$ the base of this exponential in $k$ lies between 0 and 1, so we get a nice exponential decay. The larger $\alpha$, the closer the base gets to 1 and thus the slower the exponential decay gets. So adding another out-edge to an already high degree vertex still contributes significantly. For $\alpha$ close to 0, the base also gets close to 0, and thus the exponential decay is way faster. So adding another out-edge only contributes significantly if the vertex was low degree before.

For negative $\alpha$, the base of the exponential is negative too. So the marginal contribution will alternate in sign depending on parity of $k$. So a negative decay parameter $\alpha$ is difficult to interpret as having a reasonable effect, unless the model aims to treat even degrees differently than odd degrees.

### iv.

As explained in **iii**, choosing $\alpha$ close to 0 would not make sense in this scenario, since adding an additional edge to already active (so high-degree) vertices only has a very small effect on the `gwodegree` statistic. Choosing $\alpha$ negative doesn't make sense either since we don't want the statistic to depend on the parity of the degree. So we choose $\alpha$ large. This means that even for high degree vertices, adding another edge increases the `gwodegree` statistic significantly. But note that no matter how large $\alpha$, the effect of adding the 100th edge will never be larger than the effect of adding the 1st edge. If we are hoping for a statistic where adding one edge to a high degree vertex has a larger effect than adding one edge to a low degree vertex, then we should choose an entirely different statistic.

So we should choose $\alpha$ moderately large, such that the decay of the marginal is slow. Like that adding out-edges to high-degree vertices still contributes significantly.
